//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        public int borrowing_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<System.DateTime> borrow_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
